filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
      # Оставляем только наш API-контейнер
      - drop_event:
          when:
            not:
              equals:
                container.name: "engagement_api"
      # Теперь безопасно декодим JSON из поля message
      - decode_json_fields:
          fields: ["message"]
          target: ""              # в корень
          overwrite_keys: true
          add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]

setup.template.enabled: false
setup.ilm.enabled: false
